### ISSUE TITLE
Support for newer Turbomole versions

### ISSUE THREAD

**Issue by davidwaroquiers** [Matgenix/turbomoleio#2]
Turbomoleio is currently "guaranteed" to work with Turbomole version 7.3. Two new versions (7.4 and 7.5) have been released since.

Here are the different thoughts about this issue:

- When adapting turbomoleio to the newer versions, how backward compatible should turbomoleio be with respect to the older versions. Mainly two possibilities:
  - (A) Tie a given version of turbomoleio to a given version of Turbomole. Pros: latest version of turbomoleio supports latest version of Turbomole, easier to implement and manage. Cons: you may not benefit from the newer turbomoleio features (even if they are not really tied to a new feature in Turbomole), you may not be able to read/parse old outputs with the newer version of turbomoleio
  - (B) Support multiple versions of Turbomole. Pros: the latest version of turbomoleio support the latest version of Turbomole + older versions (which ones?). Cons: more difficult to implement and maintain.
- Testing:
  - If (A): bot the unit and integration tests are updated accordingly
  - If (B): the unit tests need to have reference files for all supported Turbomole versions. The integration tests must be run with all supported Turbomole versions
- One intermediate solution in (B) could be to support *parsing* for the last N (N "large", e.g. 5) versions of Turbomole and to support input preparation for the last M (M "small", e.g. 3, or even just 1) versions of Turbomole. Indeed, it is more likely that a user is willling to work (parse the outputs) with TM files generated from runs with an older TM than willing to actually run an older version of TM. If M is equal to 1 (i.e. last version of turbomoleio only support the last version of Turbomole for the input generation, but supports the N last versions of Turbomole for output parsing), then integration tests only need to be run with one version of TM, which is most likely much easier.

@karnajitsen and @gpetretto , what are your thoughts about this ?

Best

**Comment by davidwaroquiers** [comment]
Summary of discussion with @gpetretto 

Most likely, supporting older versions of Turbomole for input AND output will be difficult. Indeed this requires the developer to have previous versions of Turbomole on its own computer in order to run the integration tests.

The best solution thus seems to support parsing for older versions of Turbomole (tests about that will be unit tests, with specific reference files for each TM version). Then the latest turbomoleio supports only (at least is "guaranteed" to support) the latests TM version (and the integration tests are run with the latest TM version).

About the support for older TM versions for the parsing of the outputs:
- The Data and Files object should not change much. If an additional element is parsed with a new version of TM, when parsing older TM files, this element will just be set to None (same if something is not output anymore and thus not parsed anymore with a new version, even if this is probably less likely to occur).
- The parsing needs to deal with multiple versions. The version can be directly set from the very beginning of the parsing. Then for the "switching" between TM versions, different solutions are possible:
   - Frozen parser for each Parser (but then a lot of code repetitions)
   - Inheritance (one Base parser and then specific parsers overriding or modifying the parsing of specific TM versions)
   - Conditions (if version == ...) in the Parser methods directly

This latter choice will depend on how different the parsing is. If there are not many differences, probably the last option with conditions is ok but if the output files are changing a lot, we'd need something different.

We need a tool to "dry-run" the integration tests without raising the Assertion error. This allows to list the differences and point out the biggest potential issues (e.g. something was parsed in the previous TM version but then becomes None, i.e. not parsed, in the new TM version).

From what it looks like, a lot of differences come from changes in default values (i.e. the control file is changed after running define).

**Comment by davidwaroquiers** [comment]
Tool for dry-running has been implemented and is merged in develop (see #3 ).

@karnajitsen What do you think about above questions ?

**Comment by karnajitsen** [comment]
Maintaining downward compatibility will be good, but this really depends how much is the change required for newer version. But it can be limited for the few of the previous versions.

In case the changes are huge (which I dont think the case for 7.3 to 7.5) we should take the option A and an interface which can load proper tmio version from the user given TM version. In this way it will be simpler to develop and manage as you said.

**Comment by davidwaroquiers** [comment]
@karnajitsen I think it is manageable to do the intermediate in which the parsing is still tested for older versions as well.
So should we agree on the following:
The latest version of turbomoleio supports everything for the latest version of TurboMole:
- input generation (basically DefineRunner)
- datagroups, control, and other "datagroup-like" files
- output parsing

The latest version of turbomoleio also supports parsing for files generated with older versions (at this stage: 7.3, 7.4 and 7.5, we could decide later on how many old versions of TM to support there). This is basically what is in the turbomoleio.output.

In that case, integration tests are run only with the latest version of TM (the one supported by the specific version of turbomoleio). For the unit tests, output files from older versions need to be kept and tested, so we need to rearrange a little bit the test files.

Lastly, concerning versions of turbomoleio, currently:
- turbomoleio v1.0.0 supports 7.3
I propose we continue as:
- turbomoleio v1.0.x supports 7.3
- turbomoleio v1.1.x supports 7.4
- turbomoleio v1.2.x supports 7.5
- ...

If at some point, we have to break backward compatibility for the parsing, we go to turbomoleio v2.y.x.

What are your thoughts @karnajitsen and @gpetretto ?

**Comment by davidwaroquiers** [comment]
Done. Procedure is described in the developer documentation.
